Update PaloAppDownloadTest

diff --git a/Splunk/PaloAppDownloadTest b/Splunk/PaloAppDownloadTest
--- a/Splunk/PaloAppDownloadTest
+++ b/Splunk/PaloAppDownloadTest
@@ -3,6 +3,25 @@ export SPLUNK_USERNAME="sysadmin"
 export SPLUNK_PASSWORD="Changeme1!"
 export SPLUNK_HOME="/opt/splunk"
 
+
+#We need to make sure SSL verification is disabled, just in case.
+
+# Store original SSL setting
+ORIGINAL_SSL_SETTING=${SPLUNK_OPTIMIZE_SSL_CERTIFICATE_VALIDATION:-true}
+
+# Function to restore SSL settings
+restore_ssl_settings() {
+    export SPLUNK_OPTIMIZE_SSL_CERTIFICATE_VALIDATION=$ORIGINAL_SSL_SETTING
+    echo "Restored SSL verification to original setting"
+}
+
+# Set trap to ensure cleanup on exit
+trap restore_ssl_settings EXIT
+
+# Temporarily disable SSL verification
+export SPLUNK_OPTIMIZE_SSL_CERTIFICATE_VALIDATION=false
+echo "Temporarily disabled SSL certificate verification"
+
 # Install Palo Alto add-on and app
 
 #Palo Alto Add-on
@@ -10,3 +29,13 @@ $SPLUNK_HOME/bin/splunk install app https://api.splunkbase.splunk.com/api/v2/app
 
 #Palo Alto App
 $SPLUNK_HOME/bin/splunk install app https://api.splunkbase.splunk.com/api/v2/apps/7505/releases/1.0.1/download/?origin=sb&lead=false
+# Explicit cleanup (optional, as trap will handle it)
+restore_ssl_settings
+
+
+
+
+
+
+
+
